CREATE DATABASE blog CHARACTER SET = utf8;

CREATE TABLE blog.posts (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255),
  body TEXT,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

